# 01 - Exploración inicial del dataset Cora

En este notebook vamos a cargar el conjunto de datos Cora, analizar su estructura básica y construir el grafo de citaciones usando NetworkX.

Los objetivos iniciales son:

- Leer los archivos `cora.content` y `cora.cites`.
- Contar el número de nodos.
- Contar el número de aristas.
- Ver las clases disponibles.
- Construir el grafo con NetworkX.

In [4]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

In [ ]:
contenido = pd.read_csv("../data/raw/cora.content", sep="\t", header=None)
contenido.head()
# la columna 0 se corresponde al id del nodo, las columnas 1 a 1433 corresponden al los atriibutos 
# de palabra y la columna 1434 se corresponde a la clase a la que pertenece cada nodo

,0,1,2,3,4,5,6,7,8,9,...,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434
0,31336,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,Neural_Networks
1,1061127,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Rule_Learning
2,1106406,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
3,13195,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
4,37879,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Probabilistic_Methods

In [11]:
citas = pd.read_csv("../data/raw/cora.cites", sep="\t", header=None)
citas.head()
# primera columna es el articulo citado y la segunda el que lo cita

    0        1
0  35     1033
1  35   103482
2  35   103515
3  35  1050679
4  35  1103960

In [15]:
contenido.shape

(2708, 1435)

In [16]:
citas.shape

(5429, 2)

## Renombrado de columnas

A continuación, vamos a cambiar el nombre de las columnas del dataset para facilitar la comprensión y el trabajo con los datos.

El archivo `cora.content` no incluye nombres de columnas, por lo que inicialmente aparecen numeradas automáticamente. Para trabajar de forma más clara, asignaremos nombres descriptivos:

- `articulo_id`: identificador del artículo.
- `palabra_0`, `palabra_1`, ..., `palabra_1432`: atributos que indican la presencia o ausencia de palabras en el artículo.
- `clase`: categoría temática del artículo.

También renombraremos las columnas del archivo `cora.cites` para identificar claramente qué artículo cita y qué artículo es citado.

In [19]:
num_features = contenido.shape[1] - 2 # nos da el numero de columnas de las palabras

columnas = ["articulo_id"] + [f"palabra_{i}" for i in range(num_features)] + ["clase"]

contenido.columns = columnas

contenido.head()

,articulo_id,palabra_0,palabra_1,palabra_2,palabra_3,palabra_4,palabra_5,palabra_6,palabra_7,palabra_8,...,palabra_1424,palabra_1425,palabra_1426,palabra_1427,palabra_1428,palabra_1429,palabra_1430,palabra_1431,palabra_1432,clase
0,31336,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,Neural_Networks
1,1061127,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Rule_Learning
2,1106406,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
3,13195,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
4,37879,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Probabilistic_Methods

In [20]:
citas.columns = ["articulo_citado_id", "articulo_citante_id"]

citas.head()

   articulo_citado_id  articulo_citante_id
0                  35                 1033
1                  35               103482
2                  35               103515
3                  35              1050679
4                  35              1103960